extends Node

var arrow = load("res://Prototypes/Clicker/Assets/arrow.png")
var pointing = load("res://Prototypes/Clicker/Assets/clickable.png")

@onready var yellow_perks_info : Dictionary = {
	"17" = {"ID" : 1, "name" : "Liquid Tungsten Fuel",
		"description" : "Useful for drinking water or holding sulfuric acid.[br][br]Increases your click points by 17", 
		"region" : {"x" : 0, "w": 160, "y" : 0, "h" : 160}, "price" : 1670, 
		"value" : 17, "bought" : false, "available" : false}, 
	"25" = {"ID" : 2, "name" : "RGB Laboratory", 
		"description" : "A laboratory to play with substances of different colors or something.[br][br]Increases your click points by 25", 
		"region" : {"x" : 160, "w": 160, "y" : 0, "h" : 160}, "price" : 10000, 
		"value" : 25, "bought" : false, "available" : false}, 
	"10" = {"ID" : 3, "name" : "Medic Room", 
		"description" : "Get your blaster injuries treated.[br][br]Increases your click points by 10", 
		"region" : {"x" : 320, "w": 160, "y" : 0, "h" : 160}, "price" : 620, 
		"value" : 10, "bought" : false, "available" : false}, 
	"12" = {"ID" : 4, "name" : "Very Magnifying Glass", 
		"description" : "See what mysteries the universe holds.[br][br]Increases your click points by 12",
		"region" : {"x" : 480, "w": 160, "y" : 0, "h" : 160}, "price" : 870, 
		"value" : 12, "bought" : false, "available" : false}, 
	"16" = {"ID" : 5, "name" : "Infirmary Module", 
		"description" : "If you have a little boo-boo, come to the infirmary to get a dinosaur bandaid.[br][br]Increases your click points by 16", 
		"region" : {"x" : 640, "w": 160, "y" : 0, "h" : 160}, "price" : 1490, 
		"value" : 16, "bought" : false, "available" : false}, 
	"1" = {"ID" : 6, "name" : "Driving Aid Liquid", 
		"description" : "Unlock all your cognitive capacities by getting wasted.[br][br]Increases your click points by 1", 
		"region" : {"x" : 800, "w": 160, "y" : 0, "h" : 160}, "price" : 10, 
		"value" : 1, "bought" : true, "available" : true}, 
	"8" = {"ID" : 7, "name" : "Industrial DIY Burger", 
		"description" : "Press your smash burgers to an atomic level![br][br]Increases your click points by 8", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 410, 
		"value" : 8, "bought" : false, "available" : false}, 
	"9" = {"ID" : 8, "name" : "Molecular Wiggler", 
		"description" : "Wiggle your molecules.[br][br]Increases your click points by 9", 
		"region" : {"x" : 160, "w": 160, "y" : 160, "h" : 160}, "price" : 510, 
		"value" : 9, "bought" : false, "available" : false}, 
	"15" = {"ID" : 9, "name" : "Portable Storage", 
		"description" : "Alien technology that allows you to put things in here and easily take them with you.[br][br]Increases your click points by 15", 
		"region" : {"x" : 320, "w": 160, "y" : 160, "h" : 160}, "price" : 1320, 
		"value" : 15, "bought" : false, "available" : false}, 
	"11" = {"ID" : 10, "name" : "V.I.D", 
		"description" : "V.I.D or Vector Input Device, our latest technology to control vehicles.[br][br]Increases your click points by 11", 
		"region" : {"x" : 480, "w": 160, "y" : 160, "h" : 160}, "price" : 740, 
		"value" : 11, "bought" : false, "available" : false},
	"4" = {"ID" : 11, "name" : "Emergency Sonar", 
		"description" : "In case of electric blackout, press this to emit a multidirectional sound wave.[br][br]Increases your click points by 4", 
		"region" : {"x" : 640, "w": 160, "y" : 160, "h" : 160}, "price" : 110, 
		"value" : 4, "bought" : false, "available" : false},
	"5" = {"ID" : 12, "name" : "V.C.K", 
		"description" : "Very Cool Keys. Hell yeah.[br][br]Increases your click points by 5", 
		"region" : {"x" : 800, "w": 160, "y" : 160, "h" : 160}, "price" : 170, 
		"value" : 5, "bought" : false, "available" : false}, 
	"6" = {"ID" : 13, "name" : "Magnetic Orientator", 
		"description" : "A device that points to the closest magnetic field. Useless if you have eyes to see the planet.[br][br]Increases your click points by 6", 
		"region" : {"x" : 0, "w": 160, "y" : 320, "h" : 160}, "price" : 240, 
		"value" : 6, "bought" : false, "available" : false}, 
	"7" = {"ID" : 14, "name" : "Centrifugal Tool", 
		"description" : "A tool that converts centrifugal movement into holes.[br][br]Increases your click points by 7", 
		"region" : {"x" : 160, "w": 160, "y" : 320, "h" : 160}, "price" : 320, 
		"value" : 7, "bought" : false, "available" : false}, 
	"2" = {"ID" : 15, "name" : "Liquid Container", 
		"description" : "The predecessor of the cientific cup.[br][br]Increases your click points by 2", 
		"region" : {"x" : 320, "w": 160, "y" : 320, "h" : 160}, "price" : 20, 
		"value" : 2, "bought" : false, "available" : true}, 
	"3" = {"ID" : 16, "name" : "Torque Tool", 
		"description" : "Apply torque to anything that has a hex head.[br][br]Increases your click points by 3", 
		"region" : {"x" : 480, "w": 160, "y" : 320, "h" : 160}, "price" : 60, 
		"value" : 3, "bought" : false, "available" : false}, 
	"19" = {"ID" : 17, "name" : "Linear Tool", 
		"description" : "Make use of multiple linear movements to separate molecules at a macroscopic level.[br][br]Increases your click points by 19", 
		"region" : {"x" : 640, "w": 160, "y" : 320, "h" : 160}, "price" : 2060, 
		"value" : 19, "bought" : false, "available" : false}, 
	"18" = {"ID" : 18, "name" : "Kinetic Tool", 
		"description" : "A device to quickly convert kinetic energy into a single point of preassure and heat.[br][br]Increases your click points by 18", 
		"region" : {"x" : 800, "w": 160, "y" : 320, "h" : 160}, "price" : 1860, 
		"value" : 18, "bought" : false, "available" : false}, 
	"20" = {"ID" : 19, "name" : "Camouflage Container", 
		"description" : "A high tech liquid container that manages different camouflage coatings.[br][br]Increases your click points by 20", 
		"region" : {"x" : 0, "w": 160, "y" : 480, "h" : 160}, "price" : 2270, 
		"value" : 20, "bought" : false, "available" : false}, 
	"26" = {"ID" : 20, "name" : "AI Analysis Device", 
		"description" : "Improve your ship cognitive sensors.[br][br]Increases your click points by 26", 
		"region" : {"x" : 160, "w": 160, "y" : 480, "h" : 160}, "price" : 10000, 
		"value" : 26, "bought" : false, "available" : false}, 
	"24" = {"ID" : 21, "name" : "AI Process Device", 
		"description" : "This device allows your ship to have neuron activations.[br][br]Increases your click points by 24", 
		"region" : {"x" : 320, "w": 160, "y" : 480, "h" : 160}, "price" : 3210, 
		"value" : 24, "bought" : false, "available" : false}, 
	"23" = {"ID" : 22, "name" : "AI Output Device", 
		"description" : "Allow your ship to communicate in new ways.[br][br]Increases your click points by 23", 
		"region" : {"x" : 480, "w": 160, "y" : 480, "h" : 160}, "price" : 2960, 
		"value" : 23, "bought" : false, "available" : false}, 
	"22" = {"ID" : 23, "name" : "AI Interface Device", 
		"description" : "Provides an interface for the ship visual communications.[br][br]Increases your click points by 22", 
		"region" : {"x" : 640, "w": 160, "y" : 480, "h" : 160}, "price" : 2720, 
		"value" : 22, "bought" : false, "available" : false}, 
	"27" = {"ID" : 24, "name" : "AI Autopilot Device", 
		"description" : "Chillax while the AI do the hard work.[br][br]Increases your click points by 27", 
		"region" : {"x" : 800, "w": 160, "y" : 480, "h" : 160}, "price" : 10000, 
		"value" : 27, "bought" : false, "available" : false}, 
	"28" = {"ID" : 25, "name" : "AI Handler Device", 
		"description" : "Take control when the AI chillax instead of you.[br][br]Increases your click points by 28", 
		"region" : {"x" : 0, "w": 160, "y" : 640, "h" : 160}, "price" : 10000, 
		"value" : 28, "bought" : false, "available" : false},
	"14" = {"ID" : 26, "name" : "AI Command Device", 
		"description" : "Have deep conversations with the AI.[br][br]Increases your click points by 14", 
		"region" : {"x" : 160, "w": 160, "y" : 640, "h" : 160}, "price" : 1160, 
		"value" : 14, "bought" : false, "available" : false}, 
	"13" = {"ID" : 27, "name" : "Black Box", 
		"description" : "Don´t worry too much about this.[br][br]Increases your click points by 13", 
		"region" : {"x" : 320, "w": 160, "y" : 640, "h" : 160}, "price" : 1010, 
		"value" : 13, "bought" : false, "available" : false}, 
	"21" = {"ID" : 28, "name" : "Human Rations", 
		"description" : "Theres not enough space to store real food. It´s this or the pub. We already know the answer.[br][br]Increases your click points by 21", 
		"region" : {"x" : 480, "w": 160, "y" : 640, "h" : 160}, "price" : 2490, 
		"value" : 21, "bought" : false, "available" : false}
}

@onready var red_perks_info : Dictionary = {
	"1" = {"ID" : 1, "name" : "Your Parents´ House",
		"description" : "It´s about time you leave the basement...", 
		"region" : {"x" : 160, "w": 160, "y" : 160, "h" : 160}, "price" : 10, 
		"value" : 1, "bought" : false, "available" : true,
		"my_button" : null}, 
	"2" = {"ID" : 2, "name" : "Granpa´s Shed", 
		"description" : "Where it all started.", 
		"region" : {"x" : 0, "w": 160, "y" : 0, "h" : 160}, "price" : 20, 
		"value" : 2, "bought" : false, "available" : false,
		"my_button" : null}, 
	"3" = {"ID" : 3, "name" : "Gas Station", 
		"description" : "Fill up your tank while smoking for a 10% discount!", 
		"region" : {"x" : 0, "w": 160, "y" : 480, "h" : 160}, "price" : 60, 
		"value" : 3, "bought" : false, "available" : false,
		"my_button" : null}, 
	"4" = {"ID" : 4, "name" : "Convinience Store", 
		"description" : "Get an overpriced fridge magnet!",
		"region" : {"x" : 320, "w": 160, "y" : 320, "h" : 160}, "price" : 110, 
		"value" : 4, "bought" : false, "available" : false,
		"my_button" : null}, 
	"5" = {"ID" : 5, "name" : "Food Suplier", 
		"description" : "It all comes from chicken...", 
		"region" : {"x" : 480, "w": 160, "y" : 0, "h" : 160}, "price" : 170, 
		"value" : 5, "bought" : false, "available" : false,
		"my_button" : null}, 
	"6" = {"ID" : 6, "name" : "Daddy´s Quarry", 
		"description" : "Sell diamonds to buy a college degree and steal other people´s work.", 
		"region" : {"x" : 480, "w": 160, "y" : 480, "h" : 160}, "price" : 240, 
		"value" : 6, "bought" : false, "available" : false,
		"my_button" : null}, 
	"7" = {"ID" : 7, "name" : "Ancient Processor", 
		"description" : "It´s old, but it´s still smashing stuff.", 
		"region" : {"x" : 800, "w": 160, "y" : 0, "h" : 160}, "price" : 320, 
		"value" : 7, "bought" : false, "available" : false,
		"my_button" : null}, 
	"8" = {"ID" : 8, "name" : "Forge", 
		"description" : "Forge a sword, a surfboard or false money, it´s up to you!", 
		"region" : {"x" : 640, "w": 160, "y" : 0, "h" : 160}, "price" : 410, 
		"value" : 8, "bought" : false, "available" : false,
		"my_button" : null}, 
	"9" = {"ID" : 9, "name" : "Hangar", 
		"description" : "Safely store the airplane you don't own yet.", 
		"region" : {"x" : 160, "w": 160, "y" : 0, "h" : 160}, "price" : 510, 
		"value" : 9, "bought" : false, "available" : false,
		"my_button" : null}, 
	"10" = {"ID" : 10, "name" : "Themed Restaurant", 
		"description" : "Eat like a real cowboy!", 
		"region" : {"x" : 0, "w": 160, "y" : 320, "h" : 160}, "price" : 620, 
		"value" : 10, "bought" : false, "available" : false,
		"my_button" : null},
	"11" = {"ID" : 11, "name" : "Money Laundering", 
		"description" : "Got to clean all that dirty money.", 
		"region" : {"x" : 800, "w": 160, "y" : 160, "h" : 160}, "price" : 740, 
		"value" : 11, "bought" : false, "available" : false,
		"my_button" : null},
	"12" = {"ID" : 12, "name" : "Ancient Headquarters", 
		"description" : "Way to big and old fashioned, but so cool.", 
		"region" : {"x" : 480, "w": 160, "y" : 160, "h" : 160}, "price" : 870, 
		"value" : 12, "bought" : false, "available" : false,
		"my_button" : null}, 
	"13" = {"ID" : 13, "name" : "Sheriff Office", 
		"description" : "Make sure you are the only criminal in town.", 
		"region" : {"x" : 160, "w": 160, "y" : 320, "h" : 160}, "price" : 1010, 
		"value" : 13, "bought" : false, "available" : false,
		"my_button" : null}, 
	"14" = {"ID" : 14, "name" : "Tourist Apartment", 
		"description" : "Pay the mortage with oblivious tourists´ money.", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 1160, 
		"value" : 14, "bought" : false, "available" : false,
		"my_button" : null}, 
	"15" = {"ID" : 15, "name" : "Automated Factory", 
		"description" : "If you use AI in the factory you get subsidies so...", 
		"region" : {"x" : 320, "w": 160, "y" : 160, "h" : 160}, "price" : 1320, 
		"value" : 15, "bought" : false, "available" : false,
		"my_button" : null}, 
	"16" = {"ID" : 16, "name" : "Crypto Mining Camp", 
		"description" : "Graphics cards go brrrr.", 
		"region" : {"x" : 640, "w": 160, "y" : 160, "h" : 160}, "price" : 1490, 
		"value" : 16, "bought" : false, "available" : false,
		"my_button" : null}, 
	"17" = {"ID" : 17, "name" : "Militarized Outpost", 
		"description" : "If you don´t move, the tanks can´t see you.", 
		"region" : {"x" : 480, "w": 160, "y" : 320, "h" : 160}, "price" : 1670, 
		"value" : 17, "bought" : false, "available" : false,
		"my_button" : null}, 
	"18" = {"ID" : 18, "name" : "Rental Mansion", 
		"description" : "Scam cryptobros with this overpriced rental mansion.", 
		"region" : {"x" : 640, "w": 160, "y" : 320, "h" : 160}, "price" : 1860, 
		"value" : 18, "bought" : false, "available" : false,
		"my_button" : null}, 
	"19" = {"ID" : 19, "name" : "Water Fountain", 
		"description" : "Its lovely to see. Especially the pennies at the bottom...", 
		"region" : {"x" : 320, "w": 160, "y" : 0, "h" : 160}, "price" : 2060, 
		"value" : 19, "bought" : false, "available" : false,
		"my_button" : null}, 
	"20" = {"ID" : 20, "name" : "Bribed Government", 
		"description" : "Laws are for the poor.", 
		"region" : {"x" : 640, "w": 160, "y" : 480, "h" : 160}, "price" : 2270, 
		"value" : 20, "bought" : false, "available" : false,
		"my_button" : null}, 
	"21" = {"ID" : 21, "name" : "Modern Headquarters", 
		"description" : "If its too windy it wiggles.", 
		"region" : {"x" : 320, "w": 160, "y" : 480, "h" : 160}, "price" : 2490, 
		"value" : 21, "bought" : false, "available" : false,
		"my_button" : null}, 
	"22" = {"ID" : 22, "name" : "Grand Hotel", 
		"description" : "All your poweful friends need a place to sleep.", 
		"region" : {"x" : 800, "w": 160, "y" : 320, "h" : 160}, "price" : 2720, 
		"value" : 22, "bought" : false, "available" : false,
		"my_button" : null}, 
	"23" = {"ID" : 23, "name" : "Spaceship Races", 
		"description" : "Whitewash your public image giving the people what they want: Spaceships races.", 
		"region" : {"x" : 160, "w": 160, "y" : 480, "h" : 160}, "price" : 2960, 
		"value" : 23, "bought" : false, "available" : false,
		"my_button" : null}, 
	"24" = {"ID" : 24, "name" : "Space Gas Station", 
		"description" : "Two kids made this and forgot about it at the end of summer.", 
		"region" : {"x" : 800, "w": 160, "y" : 480, "h" : 160}, "price" : 3210, 
		"value" : 24, "bought" : false, "available" : false,
		"my_button" : null},
	"25" = {"ID" : 24, "name" : "joker", 
		"description" : "Two kids made this and forgot about it at the end of summer.", 
		"region" : {"x" : 800, "w": 160, "y" : 480, "h" : 160}, "price" : 3210, 
		"value" : 24, "bought" : false, "available" : false,
		"my_button" : null},  
}

@onready var blue_perks_info : Dictionary = {
	"1" = {"ID" : 1, "name" : "Your Parents´ House",
		"description" : "It´s about time you leave the basement...", 
		"region" : {"x" : 640, "w": 160, "y" : 320, "h" : 160}, "price" : 10, 
		"value" : 1, "bought" : false, "available" : true,
		"my_button" : null}, 
	"2" = {"ID" : 2, "name" : "Granpa´s Shed", 
		"description" : "Where it all started.", 
		"region" : {"x" : 0, "w": 160, "y" : 0, "h" : 160}, "price" : 20, 
		"value" : 2, "bought" : false, "available" : false,
		"my_button" : null}, 
	"3" = {"ID" : 3, "name" : "Gas Station", 
		"description" : "Fill up your tank while smoking for a 10% discount!", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 60, 
		"value" : 3, "bought" : false, "available" : false,
		"my_button" : null}, 
	"4" = {"ID" : 4, "name" : "Convinience Store", 
		"description" : "Get an overpriced fridge magnet!",
		"region" : {"x" : 800, "w": 160, "y" : 320, "h" : 160}, "price" : 110, 
		"value" : 4, "bought" : false, "available" : false,
		"my_button" : null}, 
	"5" = {"ID" : 5, "name" : "Food Suplier", 
		"description" : "It all comes from chicken...", 
		"region" : {"x" : 480, "w": 160, "y" : 0, "h" : 160}, "price" : 170, 
		"value" : 5, "bought" : false, "available" : false,
		"my_button" : null}, 
	"6" = {"ID" : 6, "name" : "Daddy´s Quarry", 
		"description" : "Sell diamonds to buy a college degree and steal other people´s work.", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 240, 
		"value" : 6, "bought" : false, "available" : false,
		"my_button" : null}, 
	"7" = {"ID" : 7, "name" : "Ancient Processor", 
		"description" : "It´s old, but it´s still smashing stuff.", 
		"region" : {"x" : 640, "w": 160, "y" : 320, "h" : 160}, "price" : 320, 
		"value" : 7, "bought" : false, "available" : false,
		"my_button" : null}, 
	"8" = {"ID" : 8, "name" : "Forge", 
		"description" : "Forge a sword, a surfboard or false money, it´s up to you!", 
		"region" : {"x" : 160, "w": 160, "y" : 0, "h" : 160}, "price" : 410, 
		"value" : 8, "bought" : false, "available" : false,
		"my_button" : null}, 
	"9" = {"ID" : 9, "name" : "Hangar", 
		"description" : "Safely store the airplane you don't own yet.", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 510, 
		"value" : 9, "bought" : false, "available" : false,
		"my_button" : null}, 
	"10" = {"ID" : 10, "name" : "Themed Restaurant", 
		"description" : "Eat like a real cowboy!", 
		"region" : {"x" : 800, "w": 160, "y" : 320, "h" : 160}, "price" : 620, 
		"value" : 10, "bought" : false, "available" : false,
		"my_button" : null},
	"11" = {"ID" : 11, "name" : "Money Laundering", ####
		"description" : "Got to clean all that dirty money.", 
		"region" : {"x" : 320, "w": 160, "y" : 0, "h" : 160}, "price" : 740, 
		"value" : 11, "bought" : false, "available" : false,
		"my_button" : null},
	"12" = {"ID" : 12, "name" : "Ancient Headquarters", 
		"description" : "Way to big and old fashioned, but so cool.", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 870, 
		"value" : 12, "bought" : false, "available" : false,
		"my_button" : null}, 
	"13" = {"ID" : 13, "name" : "Sheriff Office", 
		"description" : "Make sure you are the only criminal in town.", 
		"region" : {"x" : 640, "w": 160, "y" : 320, "h" : 160}, "price" : 1010, 
		"value" : 13, "bought" : false, "available" : false,
		"my_button" : null}, 
	"14" = {"ID" : 14, "name" : "Tourist Apartment", 
		"description" : "Pay the mortage with oblivious tourists´ money.", 
		"region" : {"x" : 0, "w": 160, "y" : 0, "h" : 160}, "price" : 1160, 
		"value" : 14, "bought" : false, "available" : false,
		"my_button" : null}, 
	"15" = {"ID" : 15, "name" : "Automated Factory", 
		"description" : "If you use AI in the factory you get subsidies so...", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 1320, 
		"value" : 15, "bought" : false, "available" : false,
		"my_button" : null}, 
	"16" = {"ID" : 16, "name" : "Crypto Mining Camp", 
		"description" : "Graphics cards go brrrr.", 
		"region" : {"x" : 800, "w": 160, "y" : 320, "h" : 160}, "price" : 1490, 
		"value" : 16, "bought" : false, "available" : false,
		"my_button" : null}, 
	"17" = {"ID" : 17, "name" : "Militarized Outpost", 
		"description" : "If you don´t move, the tanks can´t see you.", 
		"region" : {"x" : 480, "w": 160, "y" : 0, "h" : 160}, "price" : 1670, 
		"value" : 17, "bought" : false, "available" : false,
		"my_button" : null}, 
	"18" = {"ID" : 18, "name" : "Rental Mansion", 
		"description" : "Scam cryptobros with this overpriced rental mansion.", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 1860, 
		"value" : 18, "bought" : false, "available" : false,
		"my_button" : null}, 
	"19" = {"ID" : 19, "name" : "Water Fountain", 
		"description" : "Its lovely to see. Especially the pennies at the bottom...", 
		"region" : {"x" : 640, "w": 160, "y" : 320, "h" : 160}, "price" : 2060, 
		"value" : 19, "bought" : false, "available" : false,
		"my_button" : null}, 
	"20" = {"ID" : 20, "name" : "Bribed Government", 
		"description" : "Laws are for the poor.", 
		"region" : {"x" : 160, "w": 160, "y" : 0, "h" : 160}, "price" : 2270, 
		"value" : 20, "bought" : false, "available" : false,
		"my_button" : null}, 
	"21" = {"ID" : 21, "name" : "Modern Headquarters", 
		"description" : "If its too windy it wiggles.", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 2490, 
		"value" : 21, "bought" : false, "available" : false,
		"my_button" : null}, 
	"22" = {"ID" : 22, "name" : "Grand Hotel", 
		"description" : "All your poweful friends need a place to sleep.", 
		"region" : {"x" : 800, "w": 160, "y" : 320, "h" : 160}, "price" : 2720, 
		"value" : 22, "bought" : false, "available" : false,
		"my_button" : null}, 
	"23" = {"ID" : 23, "name" : "Spaceship Races", 
		"description" : "Whitewash your public image giving the people what they want: Spaceships races.", 
		"region" : {"x" : 320, "w": 160, "y" : 0, "h" : 160}, "price" : 2960, 
		"value" : 23, "bought" : false, "available" : false,
		"my_button" : null}, 
	"24" = {"ID" : 24, "name" : "Space Gas Station", 
		"description" : "Two kids made this and forgot about it at the end of summer.", 
		"region" : {"x" : 0, "w": 160, "y" : 160, "h" : 160}, "price" : 3210, 
		"value" : 24, "bought" : false, "available" : false,
		"my_button" : null},
	"25" = {"ID" : 24, "name" : "joker", 
		"description" : "Two kids made this and forgot about it at the end of summer.", 
		"region" : {"x" : 800, "w": 160, "y" : 480, "h" : 160}, "price" : 3210, 
		"value" : 24, "bought" : false, "available" : false,
		"my_button" : null},  
}


var money : int = 0 #Almacena los puntos obtenidos en el clicker

var current_step : int = 0
var selected_path : int
var mission_goal : int = 0

var active_yellow_perks : Array
var total_yellow : int = 0
var active_red_perks : Array
var total_red : int = 0

func _ready() -> void:
	Input.set_custom_mouse_cursor(arrow)
	Input.set_custom_mouse_cursor(pointing, Input.CURSOR_POINTING_HAND)
	current_step = 0


func mission_manager(current_mission : Dictionary) -> void: 
	mission_goal = current_mission.get("goal")

func scale_goal(current_mission : Dictionary) -> void:
	var processed_goal : int
	
	if current_mission.get("typeid") == 0:
		processed_goal = ceil(current_step * 10.75)
		
	elif current_mission.get("typeid") == 1:
		processed_goal = (current_step * 65)
	
	elif current_mission.get("typedid") == 2:
		processed_goal = 1
		
	mission_goal = processed_goal
