extends Node

const KOKOENG_1 = preload("res://Prototypes/Shmup/Assets/Blueprints/KOKOeng1.jpg")

var engine_0 : Dictionary = { "ID": 0, 
 "TypeID": 3, 
 "Type": "eng", 
 "Name": "ENGINE", 
 "Area": 0, 
 "Weight": 0, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0, 
 "Price": 0, 
 "Unlocked": false, 
 "Blueprint": null}

var engine_1 : Dictionary = { "ID": 1, 
 "TypeID": 3, 
 "Type": "eng", 
 "Name": "KOKO ENG MK1", 
 "Area": 0, 
 "Weight": 0.9, 
 "Speed": 0, 
 "Force": 30, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 4, 
 "Price": 120000, 
 "Unlocked": true, 
 "Blueprint": null}

var engine_2 : Dictionary = { "ID": 2, 
 "TypeID": 3, 
 "Type": "eng", 
 "Name": "KOKO ENG MK2", 
 "Area": 0, 
 "Weight": 0.7, 
 "Speed": 0, 
 "Force": 50, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 4, 
 "Price": 150000, 
 "Unlocked": true, 
 "Blueprint": null}

var engine_3 : Dictionary = { "ID": 3, 
 "TypeID": 3, 
 "Type": "eng", 
 "Name": "ARD IMPLSR", 
 "Area": 0, 
 "Weight": 0.5, 
 "Speed": 0, 
 "Force": 30, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 3, 
 "Price": 250000, 
 "Unlocked": false, 
 "Blueprint": null}

var engine_4 : Dictionary = { "ID": 4, 
 "TypeID": 3, 
 "Type": "eng", 
 "Name": "ARD AR-ION", 
 "Area": 0, 
 "Weight": 0.7, 
 "Speed": 0, 
 "Force": 40, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 3, 
 "Price": 300000, 
 "Unlocked": false, 
 "Blueprint": null}

var engine_5 : Dictionary = { "ID": 5, 
 "TypeID": 3, 
 "Type": "eng", 
 "Name": "ADOIP TE-601", 
 "Area": 0, 
 "Weight": 0.5, 
 "Speed": 0, 
 "Force": 45, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 3.5, 
 "Price": 350000, 
 "Unlocked": false, 
 "Blueprint": null }

var engine_6 : Dictionary = { "ID": 6, 
 "TypeID": 3, 
 "Type": "eng", 
 "Name": "ADOIP IJ-105", 
 "Area": 0, 
 "Weight": 0.7, 
 "Speed": 0, 
 "Force": 35, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 3.5, 
 "Price": 280000, 
 "Unlocked": false, 
 "Blueprint": null}

var engine_7 : Dictionary = { "ID": 7, 
 "TypeID": 3, 
 "Type": "eng", 
 "Name": "ADOIP JE-309", 
 "Area": 0, 
 "Weight": 0.7, 
 "Speed": 0, 
 "Force": 30, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 3.5, 
 "Price": 250000, 
 "Unlocked": false, 
 "Blueprint": null}
