extends Node

const KOKOCRG_1 = preload("res://Prototypes/Shmup/Assets/Blueprints/KOKOcrg1.jpg")


var cargo_0 : Dictionary = { "ID": 0, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "CARGO", 
 "Area": 0, 
 "Weight": 0.0, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0, 
 "Price": 0, 
 "Unlocked": false, 
 "Blueprint": null}

var cargo_1 : Dictionary = { "ID": 1, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "KOKO CRG MK1", 
 "Area": 0, 
 "Weight": 0.3, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 30, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 3, 
 "Price": 40000, 
 "Unlocked": true, 
 "Blueprint": null}

var cargo_2 : Dictionary = { "ID": 2, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "KOKO CRG MK2", 
 "Area": 0, 
 "Weight": 0.4, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 45, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 3, 
 "Price": 60000, 
 "Unlocked": true, 
 "Blueprint": null }

var cargo_3 : Dictionary = { "ID": 3, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "ARD RCMR", 
 "Area": 0, 
 "Weight": 0.1, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 20, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 1, 
 "Price": 70000, 
 "Unlocked": false, 
 "Blueprint": null }

var cargo_4 : Dictionary = { "ID": 4, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "ARD AR-KELO", 
 "Area": 0, 
 "Weight": 0.25, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 40, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 2, 
 "Price": 150000, 
 "Unlocked": false, 
 "Blueprint": null }
