extends Node

const KOKOSLD_1 = preload("res://Prototypes/Shmup/Assets/Blueprints/KOKOsld1.jpg")

var shield_0 : Dictionary = { "ID": 0, 
 "TypeID": 4, 
 "Type": "sld", 
 "Name": "SHIELD", 
 "Area": 0, 
 "Weight": 0, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0, 
 "Price": 0, 
 "Unlocked": false, 
 "Blueprint": null }

var shield_1 : Dictionary = { "ID": 1, 
 "TypeID": 4, 
 "Type": "sld", 
 "Name": "KOKO SLD MK1", 
 "Area": 0, 
 "Weight": 0.4, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 20, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 1, 
 "Price": 2000, 
 "Unlocked": true, 
 "Blueprint": null }

var shield_2 : Dictionary = { "ID": 2, 
 "TypeID": 4, 
 "Type": "sld", 
 "Name": "KOKO SLD MK2", 
 "Area": 0, 
 "Weight": 0.2, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 20, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 1, 
 "Price": 3500, 
 "Unlocked": true, 
 "Blueprint": null }

var shield_3 : Dictionary = { "ID": 3, 
 "TypeID": 4, 
 "Type": "sld", 
 "Name": "ARD PRTCTR", 
 "Area": 0, 
 "Weight": 0.5, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 30, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 1, 
 "Price": 6000, 
 "Unlocked": false, 
 "Blueprint": null }

var shield_4 : Dictionary = { "ID": 4, 
 "TypeID": 4, 
 "Type": "sld", 
 "Name": "ARD AR-GIDA", 
 "Area": 0, 
 "Weight": 0.5, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 50, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 1, 
 "Price": 10000, 
 "Unlocked": false, 
 "Blueprint": null }

var shield_5 : Dictionary = { "ID": 5, 
 "TypeID": 4, 
 "Type": "sld", 
 "Name": "ADOIP SM-238", 
 "Area": 0, 
 "Weight": 0.1, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 10, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0.2, 
 "Price": 3000, 
 "Unlocked": false, 
 "Blueprint": null }

var shield_6 : Dictionary = { "ID": 6, 
 "TypeID": 4, 
 "Type": "sld", 
 "Name": "ADOIP PH- 573", 
 "Area": 0, 
 "Weight": 0.1, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 15, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0.3, 
 "Price": 4000, 
 "Unlocked": false, 
 "Blueprint": null }

var shield_7 : Dictionary = { "ID": 7, 
 "TypeID": 4, 
 "Type": "sld", 
 "Name": "ADOIP PH- 612", 
 "Area": 0, 
 "Weight": 0.2, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 30, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0.5, 
 "Price": 10500, 
 "Unlocked": false, 
 "Blueprint": null}
