extends Node

const KOKOBDY_1 = preload("res://Prototypes/Shmup/Assets/Blueprints/KOKObdy1jpg.jpg")

var body_0 : Dictionary = { "ID": 0, 
 "TypeID": 1, 
 "Type": "bdy", 
 "Name": "BODY", 
 "Area": 0, 
 "Weight": 0, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0, 
 "Price": 0, 
 "Unlocked": false, 
 "Blueprint": null }

var body_1 : Dictionary = { "ID": 1, 
 "TypeID": 1, 
 "Type": "bdy", 
 "Name": "KOKO BDY MK1", 
 "Area": 2, 
 "Weight": 1, 
 "Speed": 300, 
 "Force": 0, 
 "HP": 100, 
 "Capacity": 10, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0, 
 "Price": 100000, 
 "Unlocked": true, 
 "Blueprint": null }

var body_2 : Dictionary = { "ID": 2, 
 "TypeID": 1, 
 "Type": "bdy", 
 "Name": "KOKO BDY MK2", 
 "Area": 1.5, 
 "Weight": 0.8, 
 "Speed": 375, 
 "Force": 0, 
 "HP": 100, 
 "Capacity": 10, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0, 
 "Price": 130000, 
 "Unlocked": true, 
 "Blueprint": null }

var body_3 : Dictionary = { "ID": 3, 
 "TypeID": 1, 
 "Type": "bdy", 
 "Name": "ARD BDKYT", 
 "Area": 2, 
 "Weight": 0.8, 
 "Speed": 420, 
 "Force": 0, 
 "HP": 80, 
 "Capacity": 8, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0, 
 "Price": 230000, 
 "Unlocked": false, 
 "Blueprint": null }

var body_4 : Dictionary = { "ID": 4, 
 "TypeID": 1, 
 "Type": "bdy", 
 "Name": "ARD AR-GO", 
 "Area": 2, 
 "Weight": 0.9, 
 "Speed": 450, 
 "Force": 0, 
 "HP": 100, 
 "Capacity": 9, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0, 
 "Price": 300000, 
 "Unlocked": false, 
 "Blueprint": null }
