extends Node

const KOKOCRG_1 = preload("res://Prototypes/Shmup/Assets/Blueprints/KOKOcrg1.jpg")


var cargo_0 : Dictionary = { "ID": 0, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "CARGO", 
 "Area": 0, 
 "Weight": 0.0, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 0, 
 "Size": 0, 
 "Price": 0, 
 "Unlocked": false, 
 "Blueprint": null}

var cargo_1 : Dictionary = { "ID": 1, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "KOKO CRG MK1", 
 "Area": 0, 
 "Weight": 0.3, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 20, 
 "Size": 3, 
 "Price": 2000, 
 "Unlocked": true, 
 "Blueprint": null }

var cargo_2 : Dictionary = { "ID": 2, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "KOKO CRG MK2", 
 "Area": 0, 
 "Weight": 0.2, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 20, 
 "Size": 3, 
 "Price": 2700, 
 "Unlocked": true, 
 "Blueprint": null }

var cargo_3 : Dictionary = { "ID": 3, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "ARD RCMR", 
 "Area": 0, 
 "Weight": 0.4, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 25, 
 "Size": 3, 
 "Price": 3000, 
 "Unlocked": false, 
 "Blueprint": null }

var cargo_4 : Dictionary = { "ID": 4, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "ARD AR-KELO", 
 "Area": 0, 
 "Weight": 0.35, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 25, 
 "Size": 2, 
 "Price": 5500, 
 "Unlocked": false, 
 "Blueprint": null }

var cargo_5 : Dictionary = { "ID": 5, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "LIVI LCB-A-01", 
 "Area": 0, 
 "Weight": 0.3, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 25, 
 "Size": 2, 
 "Price": 6000, 
 "Unlocked": false, 
 "Blueprint": null }

var cargo_6 : Dictionary = { "ID": 6, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "LIVI LCB-A-11", 
 "Area": 0, 
 "Weight": 0.3, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 28, 
 "Size": 1.7, 
 "Price": 7500, 
 "Unlocked": false, 
 "Blueprint": null }

var cargo_7 : Dictionary = { "ID": 7, 
 "TypeID": 2, 
 "Type": "crg", 
 "Name": "LIVI LCB-O-01", 
 "Area": 0, 
 "Weight": 0.2, 
 "Speed": 0, 
 "Force": 0, 
 "HP": 0, 
 "Capacity": 0, 
 "Damage": 0, 
 "Cadence": 0, 
 "Rounds": 30, 
 "Size": 2, 
 "Price": 10000, 
 "Unlocked": false, 
 "Blueprint": null }
